### ISSUE TITLE
Error with matplotlib when installing through Anaconda Prompt

### ISSUE THREAD

**Issue by danielsbridges** [livingag/pyTG43#3]
Executing `python setup.py install` in the Anaconda Prompt, everything appeared to be working until it began searching for matplotlib:

> Installed c:\programdata\anaconda3\envs\medphys\lib\site-packages\pytg43-0.3.0-py3.7.egg
> Processing dependencies for pyTG43==0.3.0
> Searching for matplotlib==2.2.0+601.g197bb59
> Reading https://pypi.org/simple/matplotlib/
> No local packages or working download links found for matplotlib==2.2.0+601.g197bb59
> error: Could not find suitable distribution for Requirement.parse('matplotlib==2.2.0+601.g197bb59')

`conda install matplotlib` installed `pkgs/main/win-64::matplotlib-3.1.3-py37_0` and `pkgs/main/win-64::matplotlib-base-3.1.3-py37h64f37c6_0` among other packages, but does pyTG43 require the deprecated 2.2.0 version of matplotlib? Can this be updated?

**Comment by SimonBiggs** [comment]
Out of interest does the following work:

```
pip install . --no-deps
```

**Comment by michaelwkudla** [comment]
This issue also persists while using the PyCharm Repository Manager. It appears to be because setup.py requires matplotlib==2.2.0+601.g197bb59. Perhaps it could be changed to matplotlib only? 
MK

**Comment by livingag** [comment]
I have updated the requirements to just have all the version numbers as the minimum.

Let me know if that works.

**Comment by michaelwkudla** [comment]
Worked for me using 

git clone https://github.com/livingag/pyTG43.git
cd pyTG43
python setup.py install

into the console. 
Thanks.
