### ISSUE TITLE
plt.show()

### ISSUE THREAD

**Issue by michaelwkudla** [livingag/pyTG43#4]
I needed to add plt.show() to the end of the dvhcomp.py file to see the final dvh curves (based on the most recent push) 
may be worth adding in. Thanks for all your work!!!

**Comment by livingag** [comment]
I have been using bokeh instead of matplotlib for these plots for a while now due to more interactivity and better integration into web-based platforms. I can re-add the matplotlib script if you want or you can just keep it from an old commit.

**Comment by michaelwkudla** [comment]
Makes sense. All good. Yea, I had to add the line:

matplotlib.use('TkAgg') 

to get interactivity for matplotlib. But it can be slow.

A question, do you happen know where/when/how the plan.rx value gets assigned? I see it comes from rp.FractionGroupSequence[0][0x300c, 0xa][0][0x300a, 0xa4].value but my DICOM export filed don't seem to include this value (it's value is '0.0', and there is no "Brachy Application Setup Dose Specification Point" assigned either). 

The plans I'm using are HDR plans from Eclipse/Brachyvision.

I've calculated the dose in my TPS before exporting as well. Currently, I'm just getting around this by manually assigning a maximum dose for the limit, essentially hardcoding the rx value. I may go back and add a method to find a reasonable X-axis limit at some point based on the DVH with the largest X% volume or something.

**Comment by livingag** [comment]
That value is meant to represent the Prescribed Dose per Fraction. I was under the impression that it referred to this value in Eclipse:

![](https://user-images.githubusercontent.com/37498259/86857454-e63b5e80-c101-11ea-81f0-8b423c6bd71c.png)

Which is just in the plan properties dialog (right-click the plan and then Properties).

The picture is for a PDR plan but it is the same for HDR plans I have as well.

**Comment by livingag** [comment]
I have thought about doing another method like you suggested as using the maximum dose in the whole array isn't really relevant due to points right next to the sources.

**Comment by michaelwkudla** [comment]
Yea. Either way it works.
Ultimately I think we all probably want to be able to pass the range we
want plotted, and then maybe a different one calculated, so having it be a
passed value to _init_ may be simpler, and then it forces the user to
decide how much they want to over calculate or not. Depends on a users
reasons for using the code.

**Comment by livingag** [comment]
The DVH calculation is independent of the range of the plot - you can pass a `grid` value greater than the default of 2.5 mm to the `get_DVH_pts()` method for each ROI you want to calculate a DVH for (line 17 in `dvhcomp.py`) if you want the calculation to be quicker, but it's not using the plan.rx value to set a range of dose values to calculate for (if that's what you mean by over calculating).

**Comment by michaelwkudla** [comment]
Ah yes true. Sorry was typing too fast I think.
It was bugging me up in get_TPS_DVH as it sets the range of values to use,
but since rx was zero, the DVH returned was a default range of -0.5 to 0.5.

It's really functional code. I suspect it will become more popular as
python and ESAPI's functionality become more popular. If I make any useful
change I'll share in the future.
Been enjoying understanding it. It's very well written!
MK
